name: build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build
        # run: npm run build -- --public-url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        run: npm run build -- --public-url https://remarkablemark.org/${{ github.event.repository.name }}

      - name: Deploy
        if: github.ref_name == 'master'
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: dist
